from   app. top.api.rest.ItemSellerGetRequest import ItemSellerGetRequest
from   app. top.api.rest.WlbWaybillIQuerydetailRequest import WlbWaybillIQuerydetailRequest
from   app. top.api.rest.VasOrderSearchRequest import VasOrderSearchRequest
from   app.top.api.rest.TradeDrugConfirmorderRequest import TradeDrugConfirmorderRequest
from   app.top.api.rest.TraderatesGetRequest import TraderatesGetRequest
from   app.top.api.rest.CainiaoOpenstorageIsvResourcedetailGetRequest import CainiaoOpenstorageIsvResourcedetailGetRequest
from   app. top.api.rest.ProductAddRequest import ProductAddRequest
from   app. top.api.rest.LogisticsAddressReachablebatchGetRequest import LogisticsAddressReachablebatchGetRequest
from   app.top.api.rest.SubuserInfoUpdateRequest import SubuserInfoUpdateRequest
from   app. top.api.rest.FenxiaoCooperationProductcatAddRequest import FenxiaoCooperationProductcatAddRequest
from   app.top.api.rest.RefundMessageAddRequest import RefundMessageAddRequest
from   app.top.api.rest.SubuserDepartmentAddRequest import SubuserDepartmentAddRequest
from   app.top.api.rest.FenxiaoProductsGetRequest import FenxiaoProductsGetRequest
from   app.top.api.rest.CainiaoWaybillIiGetRequest import CainiaoWaybillIiGetRequest
from   app.top.api.rest.TradeDrugGetRequest import TradeDrugGetRequest
from   app.top.api.rest.RegionPriceManageRequest import RegionPriceManageRequest
from   app.top.api.rest.CainiaoCntmsMailnoGetRequest import CainiaoCntmsMailnoGetRequest
from   app.top.api.rest.CainiaoCloudprintCustomaresGetRequest import CainiaoCloudprintCustomaresGetRequest
from   app.top.api.rest.FenxiaoProductGradepriceUpdateRequest import FenxiaoProductGradepriceUpdateRequest
from   app.top.api.rest.ShopcatsListGetRequest import ShopcatsListGetRequest
from   app.top.api.rest.FenxiaoRequisitionsGetRequest import FenxiaoRequisitionsGetRequest
from   app.top.api.rest.TradesSoldGetRequest import TradesSoldGetRequest
from   app.top.api.rest.FenxiaoDistributorsGetRequest import FenxiaoDistributorsGetRequest
from   app.top.api.rest.ProductGetRequest import ProductGetRequest
from   app.top.api.rest.ItemJointPropimgRequest import ItemJointPropimgRequest
from   app.top.api.rest.TmallProductSchemaUpdateRequest import TmallProductSchemaUpdateRequest
from   app.top.api.rest.CainiaoLogisticsIntelliBatchGetRequest import CainiaoLogisticsIntelliBatchGetRequest
from   app.top.api.rest.WlbItemConsignmentQueryRequest import WlbItemConsignmentQueryRequest
from   app.top.api.rest.WlbItemDeleteRequest import WlbItemDeleteRequest
from   app.top.api.rest.ItemCspuMoveRequest import ItemCspuMoveRequest
from   app.top.api.rest.TmallItemQuantityUpdateRequest import TmallItemQuantityUpdateRequest
from   app.top.api.rest.CainiaoOpenstorageResourceUpdateRequest import CainiaoOpenstorageResourceUpdateRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderRefuseRequest import FenxiaoDealerRequisitionorderRefuseRequest
from   app.top.api.rest.TmallProductTemplateGetRequest import TmallProductTemplateGetRequest
from   app.top.api.rest.WlbWmsConsignInventoryReleaseRequest import WlbWmsConsignInventoryReleaseRequest
from   app.top.api.rest.LogisticsOnlineConfirmRequest import LogisticsOnlineConfirmRequest
from   app.top.api.rest.RegionSaleQueryRequest import RegionSaleQueryRequest
from   app.top.api.rest.TmallItemDapeiTemplateUpdateRequest import TmallItemDapeiTemplateUpdateRequest
from   app.top.api.rest.OcEserviceAppointListRequest import OcEserviceAppointListRequest
from   app.top.api.rest.WlbOrderitemPageGetRequest import WlbOrderitemPageGetRequest
from   app.top.api.rest.WlbItemAuthorizationAddRequest import WlbItemAuthorizationAddRequest
from   app.top.api.rest.WlbWmsStockInOrderConfirmRequest import WlbWmsStockInOrderConfirmRequest
from   app.top.api.rest.ItemUpdateListingRequest import ItemUpdateListingRequest
from   app.top.api.rest.PromotionCouponsGetRequest import PromotionCouponsGetRequest
from   app.top.api.rest.TradeConfirmfeeGetRequest import TradeConfirmfeeGetRequest
from   app.top.api.rest.WlbOrderstatusGetRequest import WlbOrderstatusGetRequest
from   app.top.api.rest.FenxiaoOrdersGetRequest import FenxiaoOrdersGetRequest
from   app.top.api.rest.ShoprecommendShopsGetRequest import ShoprecommendShopsGetRequest
from   app.top.api.rest.WlbWmsConsignOrderNotifyRequest import WlbWmsConsignOrderNotifyRequest
from   app.top.api.rest.ItemSkuPriceUpdateRequest import ItemSkuPriceUpdateRequest
from   app.top.api.rest.ItemPriceUpdateRequest import ItemPriceUpdateRequest
from   app.top.api.rest.WlbOrderJzConsignRequest import WlbOrderJzConsignRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderCloseRequest import FenxiaoDealerRequisitionorderCloseRequest
from   app.top.api.rest.TmallProductSpecAddRequest import TmallProductSpecAddRequest
from   app.top.api.rest.TopSecretRegisterRequest import TopSecretRegisterRequest
from   app.top.api.rest.WlbTmsorderQueryRequest import WlbTmsorderQueryRequest
from   app.top.api.rest.WlbImportsResourceGetRequest import WlbImportsResourceGetRequest
from   app.top.api.rest.ItemQuantityUpdateRequest import ItemQuantityUpdateRequest
from   app.top.api.rest.FenxiaoRefundMessageAddRequest import FenxiaoRefundMessageAddRequest
from   app.top.api.rest.TmallBrandcatControlGetRequest import TmallBrandcatControlGetRequest
from   app.top.api.rest.LogisticsOrdersGetRequest import LogisticsOrdersGetRequest
from   app.top.api.rest.WlbWmsConsignInventoryOccupancyRequest import WlbWmsConsignInventoryOccupancyRequest
from   app.top.api.rest.TradeAmountGetRequest import TradeAmountGetRequest
from   app.top.api.rest.WlbWaybillIFullupdateRequest import WlbWaybillIFullupdateRequest
from   app.top.api.rest.FenxiaoOrderMessageAddRequest import FenxiaoOrderMessageAddRequest
from   app.top.api.rest.ItemJointImgRequest import ItemJointImgRequest
from   app.top.api.rest.PictureReplaceRequest import PictureReplaceRequest
from   app.top.api.rest.DeliveryTemplateUpdateRequest import DeliveryTemplateUpdateRequest
from   app.top.api.rest.CategoryrecommendItemsGetRequest import CategoryrecommendItemsGetRequest
from   app.top.api.rest.TradeReceivetimeDelayRequest import TradeReceivetimeDelayRequest
from   app.top.api.rest.FenxiaoTrademonitorGetRequest import FenxiaoTrademonitorGetRequest
from   app.top.api.rest.CainiaoBimTradeorderConsignRequest import CainiaoBimTradeorderConsignRequest
from   app.top.api.rest.SubuserDepartmentDeleteRequest import SubuserDepartmentDeleteRequest
from   app.top.api.rest.TmallItemOuteridUpdateRequest import TmallItemOuteridUpdateRequest
from   app.top.api.rest.WlbTradeorderGetRequest import WlbTradeorderGetRequest
from   app.top.api.rest.WlbWmsSkuCombinationCreateUpdateRequest import WlbWmsSkuCombinationCreateUpdateRequest
from   app.top.api.rest.WmsOrderWarehouseRouteGetRequest import WmsOrderWarehouseRouteGetRequest
from   app.top.api.rest.WlbWmsSkuGetRequest import WlbWmsSkuGetRequest
from   app.top.api.rest.InventoryInitialItemRequest import InventoryInitialItemRequest
from   app.top.api.rest.WlbItemConsignmentPageGetRequest import WlbItemConsignmentPageGetRequest
from   app.top.api.rest.AlibabaWttOrderContractSubscribeRequest import AlibabaWttOrderContractSubscribeRequest
from   app.top.api.rest.WlbImportsWaybillGetRequest import WlbImportsWaybillGetRequest
from   app.top.api.rest.FenxiaoDiscountsGetRequest import FenxiaoDiscountsGetRequest
from   app.top.api.rest.RefundsApplyGetRequest import RefundsApplyGetRequest
from   app.top.api.rest.FenxiaoCooperationUpdateRequest import FenxiaoCooperationUpdateRequest
from   app.top.api.rest.TmallItemCombineGetRequest import TmallItemCombineGetRequest
from   app.top.api.rest.CainiaoCloudprintIsvtemplatesGetRequest import CainiaoCloudprintIsvtemplatesGetRequest
from   app.top.api.rest.ItemAddRequest import ItemAddRequest
from   app.top.api.rest.FenxiaoProductcatsGetRequest import FenxiaoProductcatsGetRequest
from   app.top.api.rest.TmallBrandcatSuiteconfGetRequest import TmallBrandcatSuiteconfGetRequest
from   app.top.api.rest.TraderateListAddRequest import TraderateListAddRequest
from   app.top.api.rest.SellercatsListAddRequest import SellercatsListAddRequest
from   app.top.api.rest.ItemImgDeleteRequest import ItemImgDeleteRequest
from   app.top.api.rest.FenxiaoProductcatAddRequest import FenxiaoProductcatAddRequest
from   app.top.api.rest.UserSellerGetRequest import UserSellerGetRequest
from   app.top.api.rest.ScitemUpdateRequest import ScitemUpdateRequest
from   app.top.api.rest.SubuserDutyDeleteRequest import SubuserDutyDeleteRequest
from   app.top.api.rest.InventoryWarehouseManageRequest import InventoryWarehouseManageRequest
from   app.top.api.rest.FenxiaoDiscountAddRequest import FenxiaoDiscountAddRequest
from   app.top.api.rest.TradeDrugOrdersGetRequest import TradeDrugOrdersGetRequest
from   app.top.api.rest.TmallProductSpecsTicketGetRequest import TmallProductSpecsTicketGetRequest
from   app.top.api.rest.WlbOrderCreateRequest import WlbOrderCreateRequest
from   app.top.api.rest.RegionPriceCancleRequest import RegionPriceCancleRequest
from   app.top.api.rest.TimeGetRequest import TimeGetRequest
from   app.top.api.rest.InventoryQueryRequest import InventoryQueryRequest
from   app.top.api.rest.ItemUpdateRequest import ItemUpdateRequest
from   app.top.api.rest.FenxiaoProductMapDeleteRequest import FenxiaoProductMapDeleteRequest
from   app.top.api.rest.SubuserEmployeeUpdateRequest import SubuserEmployeeUpdateRequest
from   app.top.api.rest.PictureGetRequest import PictureGetRequest
from   app.top.api.rest.ProductsGetRequest import ProductsGetRequest
from   app.top.api.rest.LogisticsAddressReachableRequest import LogisticsAddressReachableRequest
from   app.top.api.rest.FenxiaoProductImageUploadRequest import FenxiaoProductImageUploadRequest
from   app.top.api.rest.SubuserFullinfoGetRequest import SubuserFullinfoGetRequest
from   app.top.api.rest.RefundMessagesGetRequest import RefundMessagesGetRequest
from   app.top.api.rest.FenxiaoGradeAddRequest import FenxiaoGradeAddRequest
from   app.top.api.rest.TopSecretGetRequest import TopSecretGetRequest
from   app.top.api.rest.TmallItemIncrementUpdateSchemaGetRequest import TmallItemIncrementUpdateSchemaGetRequest
from   app.top.api.rest.TradeCloseRequest import TradeCloseRequest
from   app.top.api.rest.PromotionLimitdiscountDetailGetRequest import PromotionLimitdiscountDetailGetRequest
from   app.top.api.rest.WlbWmsInventoryProfitlossGetRequest import WlbWmsInventoryProfitlossGetRequest
from   app.top.api.rest.WlbWaybillIProductRequest import WlbWaybillIProductRequest
from   app.top.api.rest.WlbWlborderGetRequest import WlbWlborderGetRequest
from   app.top.api.rest.WlbWmsSkuCreateRequest import WlbWmsSkuCreateRequest
from   app.top.api.rest.ShopGetRequest import ShopGetRequest
from   app.top.api.rest.RefundRefuseRequest import RefundRefuseRequest
from   app.top.api.rest.WlbItemBatchQueryRequest import WlbItemBatchQueryRequest
from   app.top.api.rest.TmallItemDapeiTemplateGetRequest import TmallItemDapeiTemplateGetRequest
from   app.top.api.rest.SellercatsListGetRequest import SellercatsListGetRequest
from   app.top.api.rest.ItempropvaluesGetRequest import ItempropvaluesGetRequest
from   app.top.api.rest.TmallItemSchemaAddRequest import TmallItemSchemaAddRequest
from   app.top.api.rest.CainiaoWaybillIiQueryByTradecodeRequest import CainiaoWaybillIiQueryByTradecodeRequest
from   app.top.api.rest.InventoryWarehouseQueryRequest import InventoryWarehouseQueryRequest
from   app.top.api.rest.SubuserDutysGetRequest import SubuserDutysGetRequest
from   app.top.api.rest.WlbSubscriptionQueryRequest import WlbSubscriptionQueryRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderModifyRequest import FenxiaoDealerRequisitionorderModifyRequest
from   app.top.api.rest.CainiaoCloudprintClientinfoPutRequest import CainiaoCloudprintClientinfoPutRequest
from   app.top.api.rest.WlbWmsConsignOutstockGetRequest import WlbWmsConsignOutstockGetRequest
from   app.top.api.rest.TmallItemPriceUpdateRequest import TmallItemPriceUpdateRequest
from   app.top.api.rest.DrugShopListRequest import DrugShopListRequest
from   app.top.api.rest.ItemIncrementUpdateSchemaGetRequest import ItemIncrementUpdateSchemaGetRequest
from   app.top.api.rest.WlbImportsOrderCancelRequest import WlbImportsOrderCancelRequest
from   app.top.api.rest.TradesSoldIncrementvGetRequest import TradesSoldIncrementvGetRequest
from   app.top.api.rest.TradeFullinfoGetRequest import TradeFullinfoGetRequest
from   app.top.api.rest.TmallProductSchemaMatchRequest import TmallProductSchemaMatchRequest
from   app.top.api.rest.WlbItemMapGetRequest import WlbItemMapGetRequest
from   app.top.api.rest.WlbItemAddRequest import WlbItemAddRequest
from   app.top.api.rest.TmallItemAddSchemaGetRequest import TmallItemAddSchemaGetRequest
from   app.top.api.rest.WlbOrderPageGetRequest import WlbOrderPageGetRequest
from   app.top.api.rest.CainiaoCbossWorkplatformWorkorderTaskNotifyRequest import CainiaoCbossWorkplatformWorkorderTaskNotifyRequest
from   app.top.api.rest.ItemrecommendItemsGetRequest import ItemrecommendItemsGetRequest
from   app.top.api.rest.FenxiaoProductUpdateRequest import FenxiaoProductUpdateRequest
from   app.top.api.rest.SubuserEmployeeAddRequest import SubuserEmployeeAddRequest
from   app.top.api.rest.LogisticsOnlineCancelRequest import LogisticsOnlineCancelRequest
from   app.top.api.rest.CainiaoLogisticsIntelliGetRequest import CainiaoLogisticsIntelliGetRequest
from   app.top.api.rest.ItemsSellerListGetRequest import ItemsSellerListGetRequest
from   app.top.api.rest.WlbWmsStockInBillGetRequest import WlbWmsStockInBillGetRequest
from   app.top.api.rest.PromotionLimitdiscountGetRequest import PromotionLimitdiscountGetRequest
from   app.top.api.rest.WlbInventoryDetailGetRequest import WlbInventoryDetailGetRequest
from   app.top.api.rest.TmallProductSchemaAddRequest import TmallProductSchemaAddRequest
from   app.top.api.rest.WlbOrderdetailDateGetRequest import WlbOrderdetailDateGetRequest
from   app.top.api.rest.TraderateAddRequest import TraderateAddRequest
from   app.top.api.rest.ItemSchemaIncrementUpdateRequest import ItemSchemaIncrementUpdateRequest
from   app.top.api.rest.SubuserDepartmentUpdateRequest import SubuserDepartmentUpdateRequest
from   app.top.api.rest.WlbWmsConsignBillGetRequest import WlbWmsConsignBillGetRequest
from   app.top.api.rest.CainiaoCloudprintCustomareaUpdateRequest import CainiaoCloudprintCustomareaUpdateRequest
from   app.top.api.rest.FenxiaoDistributorItemsGetRequest import FenxiaoDistributorItemsGetRequest
from   app.top.api.rest.CainiaoCloudprintTemplatesMigrateRequest import CainiaoCloudprintTemplatesMigrateRequest
from   app.top.api.rest.DeliveryTemplateGetRequest import DeliveryTemplateGetRequest
from   app.top.api.rest.RefundsReceiveGetRequest import RefundsReceiveGetRequest
from   app.top.api.rest.CainiaoCloudprintMystdtemplatesGetRequest import CainiaoCloudprintMystdtemplatesGetRequest
from   app.top.api.rest.AlibabaAlitjOrderRealnamecardInfoSubmitRequest import AlibabaAlitjOrderRealnamecardInfoSubmitRequest
from   app.top.api.rest.SkusCustomGetRequest import SkusCustomGetRequest
from   app.top.api.rest.ItemsCustomGetRequest import ItemsCustomGetRequest
from   app.top.api.rest.CainiaoCloudprintStdtemplatesGetRequest import CainiaoCloudprintStdtemplatesGetRequest
from   app.top.api.rest.TmallProductSchemaGetRequest import TmallProductSchemaGetRequest
from   app.top.api.rest.TicketItemAddRequest import TicketItemAddRequest
from   app.top.api.rest.WlbWmsStockOutOrderNotifyRequest import WlbWmsStockOutOrderNotifyRequest
from   app.top.api.rest.TmallProductBooksAddRequest import TmallProductBooksAddRequest
from   app.top.api.rest.WlbOutInventoryChangeNotifyRequest import WlbOutInventoryChangeNotifyRequest
from   app.top.api.rest.TopAuthTokenRefreshRequest import TopAuthTokenRefreshRequest
from   app.top.api.rest.SkusQuantityUpdateRequest import SkusQuantityUpdateRequest
from   app.top.api.rest.CainiaoCbossWorkplatformWorkorderCreateRequest import CainiaoCbossWorkplatformWorkorderCreateRequest
from   app.top.api.rest.CainiaoOpenstorageIsvResourceCreateRequest import CainiaoOpenstorageIsvResourceCreateRequest
from   app.top.api.rest.ItempropsGetRequest import ItempropsGetRequest
from   app.top.api.rest.CainiaoWaybillIiQueryByWaybillcodeRequest import CainiaoWaybillIiQueryByWaybillcodeRequest
from   app.top.api.rest.WlbOrderJzpartnerQueryRequest import WlbOrderJzpartnerQueryRequest
from   app.top.api.rest.TmallItemSchemaUpdateRequest import TmallItemSchemaUpdateRequest
from   app.top.api.rest.SellercenterRoleInfoGetRequest import SellercenterRoleInfoGetRequest
from   app.top.api.rest.FuwuSaleLinkGenRequest import FuwuSaleLinkGenRequest
from   app.top.api.rest.WlbWmsSkuUpdateRequest import WlbWmsSkuUpdateRequest
from   app.top.api.rest.WlbWmsInventoryStatusUploadRequest import WlbWmsInventoryStatusUploadRequest
from   app.top.api.rest.CainiaoOpenstorageSellerResourceCreateRequest import CainiaoOpenstorageSellerResourceCreateRequest
from   app.top.api.rest.CainiaoCbossWorkplatformOperationReplyRequest import CainiaoCbossWorkplatformOperationReplyRequest
from   app.top.api.rest.SellercenterRoleAddRequest import SellercenterRoleAddRequest
from   app.top.api.rest.InventoryStoreManageRequest import InventoryStoreManageRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderGetRequest import FenxiaoDealerRequisitionorderGetRequest
from   app.top.api.rest.ProductUpdateRequest import ProductUpdateRequest
from   app.top.api.rest.AlibabaTianjiSupplierOrderDeliveryRequest import AlibabaTianjiSupplierOrderDeliveryRequest
from   app.top.api.rest.TicketItemGetRequest import TicketItemGetRequest
from   app.top.api.rest.ProductImgUploadRequest import ProductImgUploadRequest
from   app.top.api.rest.WlbNotifyMessageConfirmRequest import WlbNotifyMessageConfirmRequest
from   app.top.api.rest.UmpPromotionGetRequest import UmpPromotionGetRequest
from   app.top.api.rest.ShopRemainshowcaseGetRequest import ShopRemainshowcaseGetRequest
from   app.top.api.rest.PictureDeleteRequest import PictureDeleteRequest
from   app.top.api.rest.PromotionActivityGetRequest import PromotionActivityGetRequest
from   app.top.api.rest.WlbWmsItemCombinationGetRequest import WlbWmsItemCombinationGetRequest
from   app.top.api.rest.WlbItemGetRequest import WlbItemGetRequest
from   app.top.api.rest.AftersaleGetRequest import AftersaleGetRequest
from   app.top.api.rest.ItemTemplatesGetRequest import ItemTemplatesGetRequest
from   app.top.api.rest.TmallItemDescModulesGetRequest import TmallItemDescModulesGetRequest
from   app.top.api.rest.ItemAnchorGetRequest import ItemAnchorGetRequest
from   app.top.api.rest.CainiaoCbossWorkplatformWorkorderProcessNotifyRequest import CainiaoCbossWorkplatformWorkorderProcessNotifyRequest
from   app.top.api.rest.AreasGetRequest import AreasGetRequest
from   app.top.api.rest.RegionWarehouseManageRequest import RegionWarehouseManageRequest
from   app.top.api.rest.ItemImgUploadRequest import ItemImgUploadRequest
from   app.top.api.rest.CainiaoOpenstorageIsvResourcesGetRequest import CainiaoOpenstorageIsvResourcesGetRequest
from   app.top.api.rest.InventoryStoreQueryRequest import InventoryStoreQueryRequest
from   app.top.api.rest.TopatsTaskDeleteRequest import TopatsTaskDeleteRequest
from   app.top.api.rest.FenxiaoGradeDeleteRequest import FenxiaoGradeDeleteRequest
from   app.top.api.rest.CainiaoWaybillIiSearchRequest import CainiaoWaybillIiSearchRequest
from   app.top.api.rest.LogisticsCompaniesGetRequest import LogisticsCompaniesGetRequest
from   app.top.api.rest.WlbWmsUnknownPackageUploadRequest import WlbWmsUnknownPackageUploadRequest
from   app.top.api.rest.TradeShippingaddressUpdateRequest import TradeShippingaddressUpdateRequest
from   app.top.api.rest.LogisticsOfflineSendRequest import LogisticsOfflineSendRequest
from   app.top.api.rest.LogisticsPartnersGetRequest import LogisticsPartnersGetRequest
from   app.top.api.rest.ItemSkuGetRequest import ItemSkuGetRequest
from   app.top.api.rest.RefundRefusereasonGetRequest import RefundRefusereasonGetRequest
from   app.top.api.rest.TradeMemoUpdateRequest import TradeMemoUpdateRequest
from   app.top.api.rest.TraderateExplainAddRequest import TraderateExplainAddRequest
from   app.top.api.rest.WlbWmsSnInfoQueryRequest import WlbWmsSnInfoQueryRequest
from   app.top.api.rest.CainiaoWaybillIiCancelRequest import CainiaoWaybillIiCancelRequest
from   app.top.api.rest.TradeSnapshotGetRequest import TradeSnapshotGetRequest
from   app.top.api.rest.AppstoreSubscribeGetRequest import AppstoreSubscribeGetRequest
from   app.top.api.rest.MarketingPromotionKfcRequest import MarketingPromotionKfcRequest
from   app.top.api.rest.WlbWmsStockInOrderNotifyRequest import WlbWmsStockInOrderNotifyRequest
from   app.top.api.rest.ItemSkuUpdateRequest import ItemSkuUpdateRequest
from   app.top.api.rest.FenxiaoOrderConfirmPaidRequest import FenxiaoOrderConfirmPaidRequest
from   app.top.api.rest.DeliveryTemplateDeleteRequest import DeliveryTemplateDeleteRequest
from   app.top.api.rest.TmallItemDapeiTemplateDeleteRequest import TmallItemDapeiTemplateDeleteRequest
from   app.top.api.rest.WlbItemQueryRequest import WlbItemQueryRequest
from   app.top.api.rest.WlbWaybillIPrintRequest import WlbWaybillIPrintRequest
from   app.top.api.rest.CainiaoWaybillIiUpdateRequest import CainiaoWaybillIiUpdateRequest
from   app.top.api.rest.CainiaoWaybillprintClientupdateGetconfigRequest import CainiaoWaybillprintClientupdateGetconfigRequest
from   app.top.api.rest.TradeOrderskuUpdateRequest import TradeOrderskuUpdateRequest
from   app.top.api.rest.CainiaoCbossWorkplatformBiztypeQuerybyidRequest import CainiaoCbossWorkplatformBiztypeQuerybyidRequest
from   app.top.api.rest.KfcKeywordSearchRequest import KfcKeywordSearchRequest
from   app.top.api.rest.WlbItemCombinationDeleteRequest import WlbItemCombinationDeleteRequest
from   app.top.api.rest.VasSubscribeGetRequest import VasSubscribeGetRequest
from   app.top.api.rest.ProductImgDeleteRequest import ProductImgDeleteRequest
from   app.top.api.rest.VasSubscSearchRequest import VasSubscSearchRequest
from   app.top.api.rest.PictureUploadRequest import PictureUploadRequest
from   app.top.api.rest.FenxiaoOrderRemarkUpdateRequest import FenxiaoOrderRemarkUpdateRequest
from   app.top.api.rest.FenxiaoProductSkusGetRequest import FenxiaoProductSkusGetRequest
from   app.top.api.rest.TradeMemoAddRequest import TradeMemoAddRequest
from   app.top.api.rest.PictureIsreferencedGetRequest import PictureIsreferencedGetRequest
from   app.top.api.rest.TmallItemSizemappingTemplateDeleteRequest import TmallItemSizemappingTemplateDeleteRequest
from   app.top.api.rest.TicketItemsGetRequest import TicketItemsGetRequest
from   app.top.api.rest.FenxiaoGradeUpdateRequest import FenxiaoGradeUpdateRequest
from   app.top.api.rest.OcEserviceAppointDeleteRequest import OcEserviceAppointDeleteRequest
from   app.top.api.rest.LogisticsOnlineSendRequest import LogisticsOnlineSendRequest
from   app.top.api.rest.TmallProductSpecPicUploadRequest import TmallProductSpecPicUploadRequest
from   app.top.api.rest.FenxiaoRefundGetRequest import FenxiaoRefundGetRequest
from   app.top.api.rest.TmallProductSuitespecsGetRequest import TmallProductSuitespecsGetRequest
from   app.top.api.rest.TmallProductUpdateSchemaGetRequest import TmallProductUpdateSchemaGetRequest
from   app.top.api.rest.WlbOrderConsignRequest import WlbOrderConsignRequest
from   app.top.api.rest.FenxiaoDistributorProductsGetRequest import FenxiaoDistributorProductsGetRequest
from   app.top.api.rest.FenxiaoCooperationGetRequest import FenxiaoCooperationGetRequest
from   app.top.api.rest.WlbWmsInventoryQueryRequest import WlbWmsInventoryQueryRequest
from   app.top.api.rest.SubuserDepartmentsGetRequest import SubuserDepartmentsGetRequest
from   app.top.api.rest.SubuserDutyUpdateRequest import SubuserDutyUpdateRequest
from   app.top.api.rest.DeliveryDrugDeliveryconfirmRequest import DeliveryDrugDeliveryconfirmRequest
from   app.top.api.rest.TmallBrandcatMetadataGetRequest import TmallBrandcatMetadataGetRequest
from   app.top.api.rest.CainiaoCbossWorkplatformBiztypeQueryallRequest import CainiaoCbossWorkplatformBiztypeQueryallRequest
from   app.top.api.rest.WlbItemMapGetByExtentityRequest import WlbItemMapGetByExtentityRequest
from   app.top.api.rest.ItemRecommendAddRequest import ItemRecommendAddRequest
from   app.top.api.rest.TmallItemSchemaIncrementUpdateRequest import TmallItemSchemaIncrementUpdateRequest
from   app.top.api.rest.HttpdnsGetRequest import HttpdnsGetRequest
from   app.top.api.rest.FenxiaoProductMapAddRequest import FenxiaoProductMapAddRequest
from   app.top.api.rest.WlbWmsCainiaoBillQueryRequest import WlbWmsCainiaoBillQueryRequest
from   app.top.api.rest.ScitemMapDeleteRequest import ScitemMapDeleteRequest
from   app.top.api.rest.PictureCategoryUpdateRequest import PictureCategoryUpdateRequest
from   app.top.api.rest.WlbWmsOrderCancelNotifyRequest import WlbWmsOrderCancelNotifyRequest
from   app.top.api.rest.WlbWaybillISearchRequest import WlbWaybillISearchRequest
from   app.top.api.rest.DrugPriceUpdateRequest import DrugPriceUpdateRequest
from   app.top.api.rest.SellercenterUserPermissionsGetRequest import SellercenterUserPermissionsGetRequest
from   app.top.api.rest.ShoprecommendItemsGetRequest import ShoprecommendItemsGetRequest
from   app.top.api.rest.TmallItemDapeiTemplateAddRequest import TmallItemDapeiTemplateAddRequest
from   app.top.api.rest.WlbImportsOrderGetRequest import WlbImportsOrderGetRequest
from   app.top.api.rest.LogisticsAddressAddRequest import LogisticsAddressAddRequest
from   app.top.api.rest.WlbOrderJzwithinsConsignRequest import WlbOrderJzwithinsConsignRequest
from   app.top.api.rest.DeliveryDrugPickupRequest import DeliveryDrugPickupRequest
from   app.top.api.rest.LogisticsAddressModifyRequest import LogisticsAddressModifyRequest
from   app.top.api.rest.ScitemMapBatchQueryRequest import ScitemMapBatchQueryRequest
from   app.top.api.rest.TmallProductSpecGetRequest import TmallProductSpecGetRequest
from   app.top.api.rest.FenxiaoProductQuantityUpdateRequest import FenxiaoProductQuantityUpdateRequest
from   app.top.api.rest.TmallItemSizemappingTemplateGetRequest import TmallItemSizemappingTemplateGetRequest
from   app.top.api.rest.PictureCategoryAddRequest import PictureCategoryAddRequest
from   app.top.api.rest.ProductPropimgUploadRequest import ProductPropimgUploadRequest
from   app.top.api.rest.FenxiaoRefundUpdateRequest import FenxiaoRefundUpdateRequest
from   app.top.api.rest.WlbItemUpdateRequest import WlbItemUpdateRequest
from   app.top.api.rest.RefundGetRequest import RefundGetRequest
from   app.top.api.rest.CainiaoOpenstorageResourcePublishRequest import CainiaoOpenstorageResourcePublishRequest
from   app.top.api.rest.WlbWmsItemCombinationDeleteRequest import WlbWmsItemCombinationDeleteRequest
from   app.top.api.rest.OcTradetagsGetRequest import OcTradetagsGetRequest
from   app.top.api.rest.InventoryOccupyAdjustRequest import InventoryOccupyAdjustRequest
from   app.top.api.rest.TopSdkFeedbackUploadRequest import TopSdkFeedbackUploadRequest
from   app.top.api.rest.TopAuthTokenCreateRequest import TopAuthTokenCreateRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderQueryRequest import FenxiaoDealerRequisitionorderQueryRequest
from   app.top.api.rest.ItemGetRequest import ItemGetRequest
from   app.top.api.rest.WlbWmsConsignOrderConfirmRequest import WlbWmsConsignOrderConfirmRequest
from   app.top.api.rest.PicturePicturesGetRequest import PicturePicturesGetRequest
from   app.top.api.rest.LogisticsOrdersDetailGetRequest import LogisticsOrdersDetailGetRequest
from   app.top.api.rest.ItemsInventoryGetRequest import ItemsInventoryGetRequest
from   app.top.api.rest.WlbOrderJzQueryRequest import WlbOrderJzQueryRequest
from   app.top.api.rest.WlbWaybillICancelRequest import WlbWaybillICancelRequest
from   app.top.api.rest.RegionWarehouseQueryRequest import RegionWarehouseQueryRequest
from   app.top.api.rest.ScitemAddRequest import ScitemAddRequest
from   app.top.api.rest.SubusersGetRequest import SubusersGetRequest
from   app.top.api.rest.CainiaoCbossWorkplatformLogisticsIscainiaoorderRequest import CainiaoCbossWorkplatformLogisticsIscainiaoorderRequest
from   app.top.api.rest.TmallItemSizemappingTemplatesListRequest import TmallItemSizemappingTemplatesListRequest
from   app.top.api.rest.TmallItemSizemappingTemplateUpdateRequest import TmallItemSizemappingTemplateUpdateRequest
from   app.top.api.rest.InventoryWarehouseGetRequest import InventoryWarehouseGetRequest
from   app.top.api.rest.ItemBarcodeUpdateRequest import ItemBarcodeUpdateRequest
from   app.top.api.rest.TmallProductAddSchemaGetRequest import TmallProductAddSchemaGetRequest
from   app.top.api.rest.FenxiaoProductcatUpdateRequest import FenxiaoProductcatUpdateRequest
from   app.top.api.rest.UserrecommendItemsGetRequest import UserrecommendItemsGetRequest
from   app.top.api.rest.FenxiaoProductSkuUpdateRequest import FenxiaoProductSkuUpdateRequest
from   app.top.api.rest.FenxiaoRefundQueryRequest import FenxiaoRefundQueryRequest
from   app.top.api.rest.ScitemMapQueryRequest import ScitemMapQueryRequest
from   app.top.api.rest.WlbImportsGeneralConsignRequest import WlbImportsGeneralConsignRequest
from   app.top.api.rest.WlbWmsItemCombinationCreateRequest import WlbWmsItemCombinationCreateRequest
from   app.top.api.rest.ItemRecommendDeleteRequest import ItemRecommendDeleteRequest
from   app.top.api.rest.WlbItemConsignmentDeleteRequest import WlbItemConsignmentDeleteRequest
from   app.top.api.rest.ItemcatsAuthorizeGetRequest import ItemcatsAuthorizeGetRequest
from   app.top.api.rest.ItemcatsGetRequest import ItemcatsGetRequest
from   app.top.api.rest.WlbItemSynchronizeDeleteRequest import WlbItemSynchronizeDeleteRequest
from   app.top.api.rest.WlbOrderCancelRequest import WlbOrderCancelRequest
from   app.top.api.rest.WlbWmsInventoryCountRequest import WlbWmsInventoryCountRequest
from   app.top.api.rest.WlbWmsStockOutBillGetRequest import WlbWmsStockOutBillGetRequest
from   app.top.api.rest.FenxiaoProductSkuAddRequest import FenxiaoProductSkuAddRequest
from   app.top.api.rest.LogisticsDummySendRequest import LogisticsDummySendRequest
from   app.top.api.rest.TradesSoldIncrementGetRequest import TradesSoldIncrementGetRequest
from   app.top.api.rest.SellercatsListUpdateRequest import SellercatsListUpdateRequest
from   app.top.api.rest.PictureUserinfoGetRequest import PictureUserinfoGetRequest
from   app.top.api.rest.ScitemOutercodeGetRequest import ScitemOutercodeGetRequest
from   app.top.api.rest.PromotionMealGetRequest import PromotionMealGetRequest
from   app.top.api.rest.RegionPriceQueryRequest import RegionPriceQueryRequest
from   app.top.api.rest.WlbImportsResourceTransferstoreGetRequest import WlbImportsResourceTransferstoreGetRequest
from   app.top.api.rest.TradePostageUpdateRequest import TradePostageUpdateRequest
from   app.top.api.rest.PictureUpdateRequest import PictureUpdateRequest
from   app.top.api.rest.TmallMarketingTmallcouponCouponApplyRequest import TmallMarketingTmallcouponCouponApplyRequest
from   app.top.api.rest.FenxiaoCooperationTerminateRequest import FenxiaoCooperationTerminateRequest
from   app.top.api.rest.ItemDeleteRequest import ItemDeleteRequest
from   app.top.api.rest.PictureCategoryGetRequest import PictureCategoryGetRequest
from   app.top.api.rest.DeliveryTemplateAddRequest import DeliveryTemplateAddRequest
from   app.top.api.rest.WlbWmsSkuInfoConfirmRequest import WlbWmsSkuInfoConfirmRequest
from   app.top.api.rest.TicketItemUpdateRequest import TicketItemUpdateRequest
from   app.top.api.rest.WlbItemSynchronizeRequest import WlbItemSynchronizeRequest
from   app.top.api.rest.PicturePicturesCountRequest import PicturePicturesCountRequest
from   app.top.api.rest.WlbInventorySyncRequest import WlbInventorySyncRequest
from   app.top.api.rest.WlbNotifyMessagePageGetRequest import WlbNotifyMessagePageGetRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderRemarkUpdateRequest import FenxiaoDealerRequisitionorderRemarkUpdateRequest
from   app.top.api.rest.WlbWmsOrderStatusUploadRequest import WlbWmsOrderStatusUploadRequest
from   app.top.api.rest.TmallItemUpdateSchemaGetRequest import TmallItemUpdateSchemaGetRequest
from   app.top.api.rest.LogisticsConsignOrderCreateandsendRequest import LogisticsConsignOrderCreateandsendRequest
from   app.top.api.rest.AppipGetRequest import AppipGetRequest
from   app.top.api.rest.CainiaoOpenstorageSellerResourcedetailGetRequest import CainiaoOpenstorageSellerResourcedetailGetRequest
from   app.top.api.rest.TmallItemShiptimeUpdateRequest import TmallItemShiptimeUpdateRequest
from   app.top.api.rest.FenxiaoCooperationAuditRequest import FenxiaoCooperationAuditRequest
from   app.top.api.rest.WlbItemCombinationCreateRequest import WlbItemCombinationCreateRequest
from   app.top.api.rest.WlbWmsReturnBillGetRequest import WlbWmsReturnBillGetRequest
from   app.top.api.rest.ItemPropimgDeleteRequest import ItemPropimgDeleteRequest
from   app.top.api.rest.SellercenterSubusersGetRequest import SellercenterSubusersGetRequest
from   app.top.api.rest.ScitemMapAddRequest import ScitemMapAddRequest
from   app.top.api.rest.FenxiaoProductImageDeleteRequest import FenxiaoProductImageDeleteRequest
from   app.top.api.rest.WlbWmsReturnOrderNotifyRequest import WlbWmsReturnOrderNotifyRequest
from   app.top.api.rest.CainiaoCntmsLogisticsOrderConsignRequest import CainiaoCntmsLogisticsOrderConsignRequest
from   app.top.api.rest.FenxiaoRefundCreateRequest import FenxiaoRefundCreateRequest
from   app.top.api.rest.WlbWmsStockPruductProcessingNotifyRequest import WlbWmsStockPruductProcessingNotifyRequest
from   app.top.api.rest.FenxiaoGradesGetRequest import FenxiaoGradesGetRequest
from   app.top.api.rest.FenxiaoProductGradepriceGetRequest import FenxiaoProductGradepriceGetRequest
from   app.top.api.rest.SellercenterRolesGetRequest import SellercenterRolesGetRequest
from   app.top.api.rest.TopatsResultGetRequest import TopatsResultGetRequest
from   app.top.api.rest.ScitemQueryRequest import ScitemQueryRequest
from   app.top.api.rest.CainiaoCloudprintIsvResourcesGetRequest import CainiaoCloudprintIsvResourcesGetRequest
from   app.top.api.rest.InventoryIpcInventorydetailGetRequest import InventoryIpcInventorydetailGetRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderAgreeRequest import FenxiaoDealerRequisitionorderAgreeRequest
from   app.top.api.rest.WlbReplenishStatisticsRequest import WlbReplenishStatisticsRequest
from   app.top.api.rest.FenxiaoDealerRequisitionorderCreateRequest import FenxiaoDealerRequisitionorderCreateRequest
from   app.top.api.rest.WlbItemConsignmentCreateRequest import WlbItemConsignmentCreateRequest
from   app.top.api.rest.FenxiaoRefundMessageGetRequest import FenxiaoRefundMessageGetRequest
from   app.top.api.rest.FenxiaoDiscountUpdateRequest import FenxiaoDiscountUpdateRequest
from   app.top.api.rest.TradeGetRequest import TradeGetRequest
from   app.top.api.rest.TmallProductMatchSchemaGetRequest import TmallProductMatchSchemaGetRequest
from   app.top.api.rest.LogisticsAddressSearchRequest import LogisticsAddressSearchRequest
from   app.top.api.rest.TmallProductSpecsGetRequest import TmallProductSpecsGetRequest
from   app.top.api.rest.LogisticsTraceSearchRequest import LogisticsTraceSearchRequest
from   app.top.api.rest.TopIpoutGetRequest import TopIpoutGetRequest
from   app.top.api.rest.TmallBrandcatPropinputGetRequest import TmallBrandcatPropinputGetRequest
from   app.top.api.rest.ProductPropimgDeleteRequest import ProductPropimgDeleteRequest
from   app.top.api.rest.DrugQuantityUpdateRequest import DrugQuantityUpdateRequest
from   app.top.api.rest.FenxiaoProductcatDeleteRequest import FenxiaoProductcatDeleteRequest
from   app.top.api.rest.WlbItemCombinationGetRequest import WlbItemCombinationGetRequest
from   app.top.api.rest.DeliveryTemplatesGetRequest import DeliveryTemplatesGetRequest
from   app.top.api.rest.InventoryInitialRequest import InventoryInitialRequest
from   app.top.api.rest.InventoryAdjustExternalRequest import InventoryAdjustExternalRequest
from   app.top.api.rest.WlbItemAuthorizationQueryRequest import WlbItemAuthorizationQueryRequest
from   app.top.api.rest.FenxiaoProductAddRequest import FenxiaoProductAddRequest
from   app.top.api.rest.WlbWmsStockOutOrderConfirmRequest import WlbWmsStockOutOrderConfirmRequest
from   app.top.api.rest.PromotionMjsGetRequest import PromotionMjsGetRequest
from   app.top.api.rest.TmallItemSizemappingTemplateCreateRequest import TmallItemSizemappingTemplateCreateRequest
from   app.top.api.rest.ItemSkuDeleteRequest import ItemSkuDeleteRequest
from   app.top.api.rest.InventoryAdjustTradeRequest import InventoryAdjustTradeRequest
from   app.top.api.rest.FenxiaoLoginUserGetRequest import FenxiaoLoginUserGetRequest
from   app.top.api.rest.OcEserviceAppointSaveRequest import OcEserviceAppointSaveRequest
from   app.top.api.rest.WlbInventorylogQueryRequest import WlbInventorylogQueryRequest
from   app.top.api.rest.WlbWmsInventoryLackUploadRequest import WlbWmsInventoryLackUploadRequest
from   app.top.api.rest.SubuserDutyAddRequest import SubuserDutyAddRequest
from   app.top.api.rest.ProductsSearchRequest import ProductsSearchRequest
from   app.top.api.rest.ScitemGetRequest import ScitemGetRequest
from   app.top.api.rest.ItemPropimgUploadRequest import ItemPropimgUploadRequest
from   app.top.api.rest.LogisticsAddressRemoveRequest import LogisticsAddressRemoveRequest
from   app.top.api.rest.ItemUpdateDelistingRequest import ItemUpdateDelistingRequest
from   app.top.api.rest.ItemsOnsaleGetRequest import ItemsOnsaleGetRequest
from   app.top.api.rest.SellercenterSubuserPermissionsRolesGetRequest import SellercenterSubuserPermissionsRolesGetRequest
from   app.top.api.rest.FenxiaoOrderCloseRequest import FenxiaoOrderCloseRequest
from   app.top.api.rest.WlbWaybillIGetRequest import WlbWaybillIGetRequest
from   app.top.api.rest.AlibabaTianjiDistributorOrderSubmitRequest import AlibabaTianjiDistributorOrderSubmitRequest
from   app.top.api.rest.FenxiaoProductSkuDeleteRequest import FenxiaoProductSkuDeleteRequest
from   app.top.api.rest.ItemSkusGetRequest import ItemSkusGetRequest
from   app.top.api.rest.FuwuScoresGetRequest import FuwuScoresGetRequest
from   app.top.api.rest.ItemSkuAddRequest import ItemSkuAddRequest
from   app.top.api.rest.CainiaoWaybillIiProductRequest import CainiaoWaybillIiProductRequest
from   app.top.api.rest.SellercenterRolemembersGetRequest import SellercenterRolemembersGetRequest
from   app.top.api.rest.ShopUpdateRequest import ShopUpdateRequest
from   app.top.api.rest.LogisticsConsignResendRequest import LogisticsConsignResendRequest
from   app.top.api.rest.TmallBrandcatSalesproGetRequest import TmallBrandcatSalesproGetRequest
